DROP TABLE IF EXISTS quote;
-- DROP TABLE IF EXISTS;
-- DROP TABLE IF EXISTS;
-- DROP TABLE IF EXISTS;
-- DROP TABLE IF EXISTS;

CREATE TABLE quote (
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY, 
    quote VARCHAR(512) NOT NULL
)

-- CREATE TABLE quote (
--     id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY, 
--     quote VARCHAR(512) NOT NULL
-- )

-- CREATE TABLE quote (
--     id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY, 
--     quote VARCHAR(512) NOT NULL
-- )

-- CREATE TABLE quote (
--     id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY, 
--     quote VARCHAR(512) NOT NULL
-- )

-- CREATE TABLE quote (
--     id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY, 
--     quote VARCHAR(512) NOT NULL
-- )